apiVersion: v1
kind: Service
metadata:
  name: mrpanel-server
  namespace: {{ .Release.Namespace }}
  labels:
    container: mrpanel-server
spec:
  ports:
    - port: 8080
      name: http
      targetPort: http
  type: ClusterIP
  selector:
    container: mrpanel-server