apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: {{ .Values.cloudflare.issuerName }}
  namespace: {{ .Release.Namespace }}
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: {{ .Values.cloudflare.secretName }}
      key: {{ .Values.cloudflare.certApiTokenKey }}