apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.cloudflare.certApiTokenKey | quote }}: {{ .Values.global.secrets.mrpanelGateway.cloudflare.apiKey | b64enc }}