apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mrpanel.infra.postgres.service.labels" $ | nindent 4 }}
spec:
  ports:
    - port: 5432
      name: postgres
  selector: {{- include "mrpanel.infra.postgres.service.labels" $ | nindent 4 }}
  type: ClusterIP
  clusterIP: None
