{{- $storageClassName := .Values.Environment.storageClass -}}

{{ define "mrpanel.infra.postgres.volume" }}
---
{{- if .createVolumesForClaims}}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .namespace }}
  name: {{ .volume }}
  labels:
    component: postgres
    purpose: {{ .purpose }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .storage }}
  accessModes:
    - ReadWriteOnce
  {{- if eq .storageClass "manual" }}
  hostPath:
    path: {{ (print .rootPath "/" .namespace  "/" .volume) | quote }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .namespace }}
  name: {{ .claim }}
  labels:
    component: postgres
    purpose: {{ .purpose }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClassName }}
  {{- if .createVolumesForClaims}}
  volumeName: {{ .volume }}
  {{- end }}
  resources:
    requests:
      storage: {{ .storage }}
{{ end }}

{{- include "mrpanel.infra.postgres.volume" (dict
  "namespace" .Release.Namespace
  "volume" "postgres-data"
  "purpose" "data"
  "claim"  (include "mrpanel.infra.postgres.volume.claim.name" "data")
  "storage" .Values.postgres.volumes.postgresData.storage
  "storageClassName" $storageClassName
  "rootPath" .Values.Environment.volumes.rootPath
  "createVolumesForClaims" .Values.Environment.createVolumesForClaims
) }}
{{ include "mrpanel.infra.postgres.volume" (dict
  "namespace" .Release.Namespace
  "volume" "postgres-backup"
  "purpose" "backup"
  "claim" (include "mrpanel.infra.postgres.volume.claim.name" "backup")
  "storage" .Values.postgres.volumes.postgresBackup.storage
  "storageClassName" $storageClassName
  "rootPath" .Values.Environment.volumes.rootPath
  "createVolumesForClaims" .Values.Environment.createVolumesForClaims
) }}

