apiVersion: v1
kind: Service
metadata:
  name: mrpanel-ui-web
  namespace: {{ .Release.Namespace }}
  labels:
    component: mrpanel-ui-web
spec:
  selector:
     container: mrpanel-ui-web
  ports:
    - port: 8081
      targetPort: http
      name: http
  type: ClusterIP
